version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
        - 'POSTGRES_PASSWORD=postgres'
        - 'POSTGRES_DB=postgres'
        - 'POSTGRES_USER=postgres'
        - 'POSTGRES_HOST_AUTH_METHOD=trust'
    ports:
      - 5432:5432
    volumes:
      - ~/docker-data/postgres/:/var/lib/postgresql/data/
# Start der DB:
# docker-compose up -d

# Status-Check der DB:
# docker-compose ps
